global-styling:
  version: VERSION
  css:
    base:
      css/base/code.css: {}
      css/base/core.css: {}
      css/base/forms.css: {}
      css/base/lists.css: {}
      css/base/media.css: {}
      css/base/table.css: {}
      css/base/typography.css: {}
    component:
      css/components/action-links.css: {}
      css/components/action-list.css: {}
      css/components/admin-list.css: {}
      css/components/system/autocomplete-loading.module.css: {}
      css/components/block.css: {}
      css/components/button.css: {}
      css/components/breadcrumb.css: {}
      css/components/compact-link.css: {}
      css/components/container-inline.module.css: {}
      css/components/content-header.css: {}
      css/components/content-main.css: {}
      css/components/datepicker.css: {}
      css/components/description.css: {}
      css/components/field.css: {}
      css/components/forms.css: {}
      css/components/forms/block-admin-display-form.css: {}
      css/components/messages.css: {}
      css/components/operations.css: {}
      css/components/page-title.css: {}
      css/components/pager.css: {}
      css/components/package-listing.css: {}
      css/components/panel.css: {}
      css/components/region.css: {}
      css/components/system/system-status-report.css: {}
      css/components/tables.css: {}
      css/components/tabs.css: {}
    layout:
      css/layout/layout.css: {}
  dependencies:
    - titus/fontello

dialog:
  version: VERSION
  css:
    component:
      css/components/dialog.css: {}

fontello:
  version: VERSION
  css:
    base:
      fonts/fontello/css/fontello.css: {}

image:
  version: VERSION
  css:
    component:
      css/components/image/image.admin.css: {}

image-widget:
  version: VERSION
  css:
    component:
      css/components/image-widget.css: {}

node:
  version: VERSION
  css:
    component:
      css/components/node/node.module.css: {}

system:
  version: VERSION
  css:
    component:
      css/components/system/system-themes-list.css: {}

vertical-tabs:
  version: VERSION
  css:
    component:
      css/components/core/vertical-tabs.css: {}

views:
  version: VERSION
  css:
    component:
      css/components/views/views.module.css: {}

views_ui:
  version: VERSION
  css:
    component:
      css/components/views_ui/views_ui.admin.css: {}
